interface AccountHead {
  id?: number;
  accountGroupCode: string | null;
  accountNo: string | null;
  accountType: string | null;
  addressId: number | null;
  alias: string | null;
  attachments: string | null;
  automatic: boolean;
  bankFormatCode: string | null;
  branchCode: string | null;
  chequeFormatFile: string | null;
  chequeFileName: string | null;
  code: string | null;
  companyCode: string | null;
  costCenter: boolean | null;
  createdOn: Date | string | null;
  createdOnBy: string | null;
  crFromAmount: number | null;
  crToAmount: number | null;
  creditDays: number | null;
  drFromAmount: number | null;
  drToAmount: number | null;
  ecsUserCode: string | null;
  hsnCode: string | null;
  inactive: boolean;
  inactiveOn: string | null;
  inactiveOnBy: string | null;
  kyc: string | null;
  lockedOn: string | null;
  lockedUpdatedOn: string | null;
  micrCode: string | null;
  name: string | null;
  nachBankCode: string | null;
  nachUniqueId: string | null;
  nbs7ItemCode: string | null;
  ndsi500ItemCode: string | null;
  panNo: string | null;
  rateInt: number | null;
  refrenceAdjust: boolean | null;
  reverseAccountGroupCode: string | null;
  roleCode: string | null;
  sharePercent: number | null;
  showInAllBranches: boolean;
  stateId: number | null;
  subLedgerCode: string | null;
  tds: boolean | null;
  tdsClassId: number | null;
  tdsEditable: boolean | null;
  tdsType: string | null;
  tax: boolean | null;
  taxCategory: string | null;
  taxClassId: number | null;
  taxNo: string | null;
  updatedOn: Date | string | null;
  updatedOnBy: string | null;
}

export type { AccountHead };
